### ISSUE TITLE
I cannot visualise the the tool-bar

### ISSUE THREAD

**Issue by jailsonfm** [zhuochun/tool-bar-md-writer#5]
Hi, 
I am trying to visualize and use the markdown toolbar but nothing is showing up.
I installed markdown-writer and I can use it successfully. I can also install the "tool-bar-md-writer" as well without any error message but nothing happen. I am using a mac 10.9.5 and atom 1.17.0. Is there anything that I should consider to make it work. It is a fabulous package and would make my life way easier. Thanks in advance.

**Comment by WagnerGMD** [comment]
Hi,

in fact there are 2 dependencies (**tool-bar** and **markdown-writer**) and I assume, you need to install the both. Once it's done, the trouble should be gone (fix).
Then did you miss it ? Did you install the **toolbar** ? And did you try to reinstall (them) ?
Because, no you didn't mention it and it's just better to clarify.

**Comment by jailsonfm** [comment]
Oh! I did everything, except the last point that was the solution!
Reinstall the two packages and restart atom as well. Thank you a lot!
I am super happy with the tools! Thanks!
